import { mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { mergeWindowsLatestYml } from "../../scripts/merge-windows-latest-yml.mjs";
import {
  expectedWindowsArtifacts,
  verifyWindowsReleaseInventory,
} from "../../scripts/verify-windows-release.mjs";

const packageJson = readFileSync(new URL("../../package.json", import.meta.url), "utf-8");
const versionMatch = /^\s*"version":\s*"([^"]+)"/m.exec(packageJson);
if (versionMatch?.[1] === undefined) {
  throw new Error("package.json version fixture is missing");
}
const version = versionMatch[1];
const x64Name = `GogMeet-${version}-x64.exe`;
const arm64Name = `GogMeet-${version}-arm64.exe`;
const x64PortableName = `GogMeet-${version}-x64-portable.exe`;
const arm64PortableName = `GogMeet-${version}-arm64-portable.exe`;
const wrongDigest = Buffer.alloc(64, 0xa5).toString("base64");

function replaceLine(yml: string, index: number, replacement: string): string {
  const lines = yml.trimEnd().split("\n");
  lines[index] = replacement;
  return `${lines.join("\n")}\n`;
}

describe("verify-windows-release", () => {
  let distDir = "";
  let validYml = "";

  beforeEach(() => {
    distDir = mkdtempSync(join(tmpdir(), "gogmeet-windows-release-"));
    const fixtures = [
      [x64Name, Buffer.alloc(2048, 0x11)],
      [arm64Name, Buffer.alloc(2304, 0x22)],
      [x64PortableName, Buffer.alloc(2560, 0x33)],
      [arm64PortableName, Buffer.alloc(2816, 0x44)],
    ] satisfies readonly (readonly [string, Buffer])[];
    for (const [name, contents] of fixtures) {
      writeFileSync(join(distDir, name), contents);
    }
    validYml = mergeWindowsLatestYml({ distDir, version }).yml;
  });

  afterEach(() => {
    rmSync(distDir, { recursive: true, force: true });
  });

  it("lists four expected artifacts for a version", () => {
    expect(expectedWindowsArtifacts(version)).toEqual([
      x64Name,
      arm64Name,
      x64PortableName,
      arm64PortableName,
    ]);
  });

  it("fails when inventory is incomplete", () => {
    const result = verifyWindowsReleaseInventory({
      files: [x64Name],
      distDir,
    });

    expect(result.ok).toBe(false);
    expect(result.missing.length).toBeGreaterThan(0);
  });

  it("accepts metadata generated by the real merger", () => {
    const result = verifyWindowsReleaseInventory({
      distDir,
      requireUpdaterYml: true,
    });

    expect(result).toEqual({
      ok: true,
      version,
      expected: [x64Name, arm64Name, x64PortableName, arm64PortableName],
      missing: [],
      message: `OK: 4 Windows artifacts present for v${version}`,
    });
  });

  const invalidMetadataCases = [
    {
      name: "stale version",
      mutate: (yml: string) => replaceLine(yml, 0, "version: 0.0.0"),
    },
    {
      name: "missing x64 entry",
      mutate: (yml: string) => {
        const lines = yml.trimEnd().split("\n");
        lines.splice(2, 3);
        return `${lines.join("\n")}\n`;
      },
    },
    {
      name: "missing arm64 entry",
      mutate: (yml: string) => {
        const lines = yml.trimEnd().split("\n");
        lines.splice(5, 3);
        return `${lines.join("\n")}\n`;
      },
    },
    {
      name: "duplicate entry",
      mutate: (yml: string) => {
        const lines = yml.trimEnd().split("\n");
        lines.splice(5, 0, ...lines.slice(2, 5));
        return `${lines.join("\n")}\n`;
      },
    },
    {
      name: "unexpected record path",
      mutate: (yml: string) => replaceLine(yml, 5, "  - url: GogMeet-unexpected.exe"),
    },
    {
      name: "portable record path",
      mutate: (yml: string) => replaceLine(yml, 5, `  - url: ${arm64PortableName}`),
    },
    {
      name: "wrong top-level path",
      mutate: (yml: string) => replaceLine(yml, 8, `path: ${arm64Name}`),
    },
    {
      name: "top-level path record disagreement",
      mutate: (yml: string) => replaceLine(yml, 8, "path: GogMeet-unexpected.exe"),
    },
    {
      name: "x64 size mismatch",
      mutate: (yml: string) => replaceLine(yml, 4, "    size: 2049"),
    },
    {
      name: "arm64 size mismatch",
      mutate: (yml: string) => replaceLine(yml, 7, "    size: 2305"),
    },
    {
      name: "x64 digest mismatch",
      mutate: (yml: string) => replaceLine(yml, 3, `    sha512: ${wrongDigest}`),
    },
    {
      name: "arm64 digest mismatch",
      mutate: (yml: string) => replaceLine(yml, 6, `    sha512: ${wrongDigest}`),
    },
    {
      name: "top-level digest mismatch",
      mutate: (yml: string) => replaceLine(yml, 9, `sha512: ${wrongDigest}`),
    },
    {
      name: "missing required field",
      mutate: (yml: string) => replaceLine(yml, 4, "    other: 2048"),
    },
    {
      name: "duplicate field",
      mutate: (yml: string) => yml.replace("    size: 2048\n", "    size: 2048\n    size: 2048\n"),
    },
    {
      name: "unexpected field",
      mutate: (yml: string) => yml.replace("files:\n", "files:\nextra: value\n"),
    },
    {
      name: "unsafe integer size",
      mutate: (yml: string) => replaceLine(yml, 4, "    size: 9007199254740992"),
    },
    {
      name: "invalid digest shape",
      mutate: (yml: string) => replaceLine(yml, 3, "    sha512: invalid"),
    },
  ] satisfies readonly {
    readonly name: string;
    readonly mutate: (yml: string) => string;
  }[];

  it.each(invalidMetadataCases)("rejects $name", ({ mutate }) => {
    writeFileSync(join(distDir, "latest.yml"), mutate(validYml), "utf-8");

    const result = verifyWindowsReleaseInventory({
      distDir,
      requireUpdaterYml: true,
    });

    expect(result.ok).toBe(false);
  });

  it("rejects same-length NSIS byte tampering after metadata generation", () => {
    writeFileSync(join(distDir, x64Name), Buffer.alloc(2048, 0x99));

    const result = verifyWindowsReleaseInventory({
      distDir,
      requireUpdaterYml: true,
    });

    expect(result.ok).toBe(false);
  });
});
